[package]
name = "knative-queue-proxy-rust"
version = "0.1.0"
authors = ["Markus Thömmes <markusthoemmes@me.com>"]
edition = "2018"

[dependencies]
envconfig = "0.7"
envconfig_derive = "0.7"
futures-intrusive = "0.3"
hyper = "0.13"
lazy_static = "1.4.0"
tokio = { version = "0.2", features = ["full"] }